<?php

namespace Youssef\BackBundle\Repository;

/**
 * AssureurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AssureurRepository extends \Doctrine\ORM\EntityRepository
{
}
