<?php

namespace Youssef\BackBundle\Repository;

/**
 * SouscriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SouscriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
