hayder:
    resource: "@HayderBundle/Resources/config/routing.yml"
    prefix:   /hayder/

youssef_front:
    resource: "@YoussefFrontBundle/Resources/config/routing.yml"
    prefix:   /youssef/front/

youssef_back:
    resource: "@YoussefBackBundle/Resources/config/routing.yml"
    prefix:   /youssef/back/

app:
    resource: '@AppBundle/Controller/'
    type: annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
