demande_index:
    path:     /
    defaults: { _controller: "HayderBundle:Demande:index" }
    methods:  GET

demande_show:
    path:     /{id}/show
    defaults: { _controller: "HayderBundle:Demande:show" }
    methods:  GET

demande_new:
    path:     /new
    defaults: { _controller: "HayderBundle:Demande:new" }
    methods:  [GET, POST]

demande_edit:
    path:     /{id}/edit
    defaults: { _controller: "HayderBundle:Demande:edit" }
    methods:  [GET, POST]

demande_delete:
    path:     /{id}/delete
    defaults: { _controller: "HayderBundle:Demande:delete" }
    methods:  DELETE




demande_index_back:
    path:     /back/
    defaults: { _controller: "HayderBundle:DemandeBack:index" }
    methods:  GET

demande_show_back:
    path:     /back/{id}/show
    defaults: { _controller: "HayderBundle:DemandeBack:show" }
    methods:  GET



demande_reponse:
    path:     /back/demande/repondre
    defaults: { _controller: "HayderBundle:DemandeBack:repondre" }
    methods:  [GET, POST]

demande_delete_back:
    path:     /back/{id}/delete
    defaults: { _controller: "HayderBundle:DemandeBack:delete" }
    methods:  DELETE
