reclamation_index:
    path:     /
    defaults: { _controller: "HayderBundle:Reclamation:index" }
    methods:  GET

reclamation_show:
    path:     /{id}/show
    defaults: { _controller: "HayderBundle:Reclamation:show" }
    methods:  GET

reclamation_new:
    path:     /new
    defaults: { _controller: "HayderBundle:Reclamation:new" }
    methods:  [GET, POST]

reclamation_edit:
    path:     /{id}/edit
    defaults: { _controller: "HayderBundle:Reclamation:edit" }
    methods:  [GET, POST]

reclamation_delete:
    path:     /{id}/delete
    defaults: { _controller: "HayderBundle:Reclamation:delete" }
    methods:  DELETE





reclamation_index_back:
    path:     /back/
    defaults: { _controller: "HayderBundle:ReclamationBack:index" }
    methods:  GET


reclamation_reponse:
    path:     /back/repondre
    defaults: { _controller: "HayderBundle:ReclamationBack:repondre" }
    methods:  [GET, POST]

reclamation_show_back:
    path:     /back/{id}/show
    defaults: { _controller: "HayderBundle:ReclamationBack:show" }
    methods:  GET




reclamation_delete_back:
    path:     /back/{id}/delete
    defaults: { _controller: "HayderBundle:ReclamationBack:delete" }
    methods:  DELETE
